import '../../core/simulation/vessel.dart';

/// Pirates content, not simulation policy. Affinities describe future bonuses only.
class HullDefinition {
  final String name, personality, affinity;
  final BehaviorMode? favoredRole;
  final double baseSpeed, hp, visualScale;
  final int crew, masts;
  int get holds => switch (name) {
    'Pirogue' => 2,
    'Barque' => 3,
    'Cog' => 12,
    'Fluyt' => 24,
    'Galleon' => 18,
    'Sloop' => 4,
    'Schooner' => 6,
    'Brig' => 8,
    'Frigate' => 10,
    'Galley' => 12,
    'Man-of-War' => 12,
    _ => 16,
  };
  int get plankCapacity => switch (name) {
    'Brig' || 'Frigate' || 'Cog' || 'Fluyt' => 2,
    'Galleon' => 3,
    'Galley' => 3,
    'Man-of-War' || 'Ship of the Line' => 5,
    _ => 1,
  };
  int get representativeCap => switch (name) {
    'Pirogue' => 3,
    'Barque' => 4,
    'Cog' => 9,
    'Fluyt' => 10,
    'Galleon' => 18,
    'Sloop' => 6,
    'Schooner' => 8,
    'Brig' => 12,
    'Frigate' => 16,
    'Galley' => 14,
    _ => 20,
  };
  double get guns => switch (name) {
    'Pirogue' => 1,
    'Barque' => 1.5,
    'Sloop' => 2,
    'Schooner' => 4,
    'Cog' => 3,
    'Fluyt' => 2,
    'Brig' => 7,
    'Galley' => 4,
    'Frigate' => 12,
    'Galleon' => 10,
    _ => 20,
  };
  const HullDefinition(
    this.name,
    this.baseSpeed,
    this.hp,
    this.crew,
    this.visualScale,
    this.masts,
    this.personality,
    this.affinity, [
    this.favoredRole,
  ]);
}

const hullCatalog = [
  HullDefinition(
    'Pirogue',
    75,
    40,
    8,
    .65,
    1,
    'Tiny escape craft; almost no guns or hold',
    'Mobility',
  ),
  HullDefinition(
    'Barque',
    69,
    55,
    12,
    .75,
    1,
    'Light coastal boat; agile and inexpensive to crew',
    'Coastal mobility',
  ),
  HullDefinition(
    'Cog',
    38,
    130,
    35,
    1.1,
    1,
    'Cargo workhorse with modest fighting power',
    'Trade',
    BehaviorMode.merchant,
  ),
  HullDefinition(
    'Fluyt',
    34,
    160,
    40,
    1.3,
    3,
    'Largest hold; lightly armed valuable prize',
    'Cargo specialist',
    BehaviorMode.merchant,
  ),
  HullDefinition(
    'Galleon',
    32,
    280,
    110,
    1.5,
    3,
    'Durable balanced prize: good guns, hold and crew',
    'Versatile heavy all-rounder',
  ),
  HullDefinition(
    'Sloop',
    66,
    80,
    18,
    .9,
    1,
    'Fast, light and slippery',
    'Starter progression; economical light work',
  ),
  HullDefinition(
    'Schooner',
    53,
    110,
    32,
    1.05,
    2,
    'Quick, versatile all-rounder',
    'Exploration',
    BehaviorMode.explorer,
  ),
  HullDefinition(
    'Brig',
    39,
    150,
    55,
    1.2,
    2,
    'Sturdy raider',
    'Boarding and loot',
    BehaviorMode.pirate,
  ),
  HullDefinition(
    'Frigate',
    30,
    210,
    90,
    1.4,
    3,
    'Heavy pirate hunter',
    'Pirate hunting',
    BehaviorMode.privateer,
  ),
  HullDefinition(
    'Galley',
    35,
    175,
    75,
    1.25,
    2,
    'Dependable trading workhorse',
    'Merchant routes',
    BehaviorMode.merchant,
  ),
  HullDefinition(
    'Man-of-War',
    20,
    360,
    160,
    1.65,
    4,
    'Slow, imposing floating fortress',
    'Major combat presence',
  ),
];
HullDefinition hullFor(String name) => hullCatalog.firstWhere(
  (h) => h.name == name,
  orElse: () => hullCatalog.firstWhere((h) => h.name == 'Sloop'),
);
